# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20160319_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='drinking',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='ehtnicity',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='food_habits',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='music',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='weight',
        ),
        migrations.AddField(
            model_name='appuser',
            name='from_age',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='partner',
            field=models.CharField(default=b'Female', max_length=6),
        ),
        migrations.AddField(
            model_name='appuser',
            name='partner_body_type',
            field=models.CharField(default=b'Average', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='partner_height',
            field=models.FloatField(blank=True, default=5.0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='to_age',
            field=models.IntegerField(blank=True, default=40),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='body_type',
            field=models.CharField(default=b'Average', max_length=10),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='height',
            field=models.FloatField(blank=True, default=5.0),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='sex',
            field=models.CharField(default=b'Male', max_length=6),
        ),
    ]
