# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20160321_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(blank=True, default=b'static/media/user_photos/default_profile.png', upload_to=b''),
        ),
    ]
